### ISSUE TITLE
Song CRUD

### ISSUE THREAD

**Issue by thraxxed** [thraxxed/soundclone#2]
Complete

- [x] Song Upload
- [x] Song Read
- [x] Song Update
- [x] Song Delete
- [x] Adequate Styling
- [x] Error Handling

**Comment by thraxxed** [comment]
At the moment Heroku is extremely picky about the type of audio files it will accept as upload.

**Comment by dwebster17** [comment]
Nice! Tiny comment: When I press enter on the song upload form, it should trigger submit on the form. This is a small detail, but it's common/important across most website forms. This can be accomplished by making sure the form is, in fact, a `<form>` html tag, and the submit button is a `<button type='submit'/>`. This will handle the enter-click logic for you (just make sure you `preventDefault` in the submit function.

**Comment by thraxxed** [comment]
All forms with text inputs now allow for pressing enter to submit, site-wide.
