### ISSUE TITLE
User Show Pages

### ISSUE THREAD

**Issue by thraxxed** [thraxxed/soundclone#4]
Complete

- [x] Display Tracks uploaded by the User
- [x] Adequate Styling

**Comment by dwebster17** [comment]
Nice work. One the track index on user show page, right now you have the deafult html styling for buttons. Can you add some custom styling to make those look more on-theme with the whole site?

**Comment by thraxxed** [comment]
I have added some extra styling to the edit/delete track buttons.  I think they look better / more in line with the styling of the rest of the site.  Thanks for the feedback!
